config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  root 'pages#index'
  get 'pages/about'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = 'FEDERICO'
    @fecha = Date.today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimerProyecto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>esta es la pagina en about</h1>
<p>Como estan todos, nosotros somos una startup de venta de animales</p>
<%= link_to 'Link al home', pages_index_path %>

app/views/pages/index.html.erb
<h1>Pages#index </h1>
<h3>Que hacessssss <%= @name %>!!!</h3>
<h3>Hoy es <%= @fecha %> </h3>
<%= link_to 'Link a About', pages_about_path %>

<p>Find me in app/views/pages/index.html.erb</p>